### ISSUE TITLE
False positive tests when bulk run

### ISSUE THREAD

**Issue by dpopchev** [nvim-neotest/neotest-python#37] opened 2022-11-18 23:23 UTC
![image](https://user-images.githubusercontent.com/25241182/202819301-63370dcd-fc2c-485b-b76c-717377812359.png)

Neovim-0.8
Python-3.8.10

PS: Note running individually has expected behavior -- inner test break outer ones
PSS: Running outer creates false positive.

**Comment by rcarriga** [comment] 2022-11-19 08:43
Can you provide some way to reproduce?

**Comment by dpopchev** [comment] 2022-11-20 08:28
Sorry, cannot reproduce. 

It was rather late when I observed the behavior; thus the issue may have been into the keyboard operator.

**Comment by dpopchev** [comment] 2022-11-20 09:35
Just re-run some test, it is a strange mixture using fixtures.
Yes, intentionally leaving out needing imports. 

```python
import pytest

@pytest.fixture
def nrpydir(tmp_path):
    return 10

# step 1, cursor here, require("neotest").run.run(vim.fn.expand("%")) produces Passes on all
def test_initializer_creates_nothing(nrpydir, tmp_path):
    assert True

# step 2, cursor here, require("neotest").run.run(vim.fn.expand("%")) produces Passes on all
# step 3, cursor here, require("neotest").run.run(), produces Passes on all Test group
# step 5, cursor here, require("neotest").run.run(), overwrites Fails with Passes
class TestCreateMthd:
    @pytest.fixture()
    def call_create(self, nrpydir):
        nrpydir.create()

    def test_a(self):
        assert True
    # step 4, cursor here, require("neotest").run.run(), produces Fail on TestRootAttr group
    class TestRootAttr:

        def test_root_dir_exists(self, nrpydir, call_create):
            assert False

        def test_root_attr(self, nrpydir, call_create, tmp_path):
            assert False

        class TestSecondCallEffect:

            class TestDefaultBehavior:

                def test_no_change(self, call_create_second_time, nrpydir, tmp_path):
                    assert False

```

**Comment by dpopchev** [comment] 2022-11-23 07:38
Just managed

**Comment by dpopchev** [comment] 2022-11-23 07:39
Son got his hands on the PC, sorry.

**Comment by rcarriga** [comment] 2022-11-23 11:10
No worries, thank you for the reproduction. I also see the same so I'll be able to take a look at some stage and figure this out :smile:

**Comment by cblessing24** [comment] 2023-07-27 15:29
I think I have a simpler reproduction for the same issue:
```python
def test_foo():
    assert True


def test_bar(fixture):  # Fixture does not exist
    assert False
```
Running all test in the file incorrectly reports that they all passed. Running them individually produces the expeced result. This seems to happen when the first test passes, a subsequent test encounters an error during setup and multiple tests are ran. Hope it helps.

**Comment by noamsto** [comment] 2024-04-11 08:18
Any updates on this?
I also see this issue when pytest-django setup fixtures throws IntegerityError

**Comment by rcarriga** [comment] 2024-08-14 15:29
Well better late than never,  I've found the issue and pushed a fix :sweat_smile: 

@noamsto I'm afraid I don't use django at all so I can't help really debug the issue there as this issue was pytest specific. My guess would be that the setup errors aren't being accounted for, similar to here, in this method https://github.com/nvim-neotest/neotest-python/blob/e5bff6dcf3cb33e6dfb97722e142961099c6021e/neotest_python/django_unittest.py#L82

**Closed by rcarriga** 2024-08-14 15:29 UTC

**Comment by noamsto** [comment] 2024-08-15 15:46
@rcarriga ,Thanks!!
I think it's the same root cause. I'm not using Django so much lately but I'll sure update if I see it happen again :)
