### ISSUE TITLE
django `python manage.py test` support?

### ISSUE THREAD

**Issue by hariom-qure** [nvim-neotest/neotest-python#51] opened 2023-07-19 22:34 UTC
I tried finding this a lot but didn't have any luck. Is it possible to run django tests?  
How do I configure it? Currently, simply running with `unittest` runner gives `settings improperly configured` error

**Comment by afrischk** [comment] 2023-07-21 05:48
Same for me. Any advice?

**Comment by afrischk** [comment] 2023-07-21 05:59
Ok. Simple workaround: `export DJANGO_SETTINGS_MODULE` Maybe you could also create an `.env` file with the env-variable.

**Comment by rcarriga** [comment] 2023-07-22 13:06
There is no django support right now and I don't use it so I won't be adding it. Open to contributions though :smile:

**Comment by afrischk** [comment] 2023-07-23 16:21
Can you give me a hint what needs to be done? I think the only difference to the python adapter is to call `python manage.py test` instead of `python -m unittest`. Do I need to implement a new test adapter like `neotest-django`? :-)

**Comment by danielebra** [comment] 2023-08-21 05:25
> Can you give me a hint what needs to be done? I think the only difference to the python adapter is to call `python manage.py test` instead of `python -m unittest`. Do I need to implement a new test adapter like `neotest-django`? :-)

Hey @afrischk ,

Did you find out what the next steps would be to perform the transformation of the test entry point?
Would be keen on adding support for [pants](https://www.pantsbuild.org/)

This is what I had in an old config file that was used with `ultest` I believe

``` vim
let test#python#runner='pytest'
let test#python#pytest#executable='pants --no-process-cleanup test'

function! PantsTransform(cmd) abort
  let single_test_cmd = substitute(a:cmd[-1], '::', ' -- -k ', '')
  let a:cmd[-1] = single_test_cmd
  return a:cmd
endfunction

let g:test#custom_transformations = {'pants': function('PantsTransform')}
let g:test#transformation = 'pants'
```

This in essence just performs the transformation on the entry point

**Comment by afrischk** [comment] 2023-08-21 06:53
Hi @danielebra,

to be honest I had not much time to look into this. I think for Django I have to implement a `NeotestUnitestRunner` that inherits from the [DiscoverRunner](https://docs.djangoproject.com/en/1.8/_modules/django/test/runner/) instead of the `TextTestRunner`. Also I think the code from the `NeotestUnitestRunner` can stay almost the same.

For `pytest` I have not looked into the code too carefully, but I think you look at the right places. You somehow need to tell `pytest` to use pants and maybe adapt the `NeotestResultCollector`? Sorry for being so vague. New insights much appreciated :-)

**Comment by danielebra** [comment] 2023-08-21 08:26
Thanks @afrischk 

I put together a very quick and dirty bandaid to just be able to invoke `pants` 

https://github.com/danielebra/neotest-python/commit/6f830f84e43bcb6c2f48b135f6a85a25e93961ca

**Comment by afrischk** [comment] 2023-08-21 08:43
Uh nice. Maybe I can do the same for django without using the `DiscoverRunner`.

**Comment by afrischk** [comment] 2023-08-21 14:40
@danielebra Can you give me a hint on how to debug python plugins in neovim? I am new to plugin development...

I know there is nvim-dap, can I use it here somehow?

**Comment by danielebra** [comment] 2023-08-21 14:53
@afrischk this was my first time editing a plug-in too. I cloned the directory and pointed my packer plug-in to the path of the local plugin and then installed it. This provided real-time feedback to changes.

I used the neotest output panel to see errors and feedback as I made changes. When using print in the plugin, I saw that feedback surfaced in the neotest floating window and output panel.

Also running the `:messages` command in nvim gave some info

I personally didn't try using dap on the plug-in, but I did invoke it a few times briefly in my target application where I was running the python tests and I think it intercepted the code at the neotest level, so that could be useful too

**Comment by afrischk** [comment] 2023-08-23 06:58
@danielebra Nice, thanks!

@rcarriga I have created a PR for django support -> #54

**Comment by sampiecz** [comment] 2023-11-08 19:22
Thank you for creating that branch / PR @afrischk :muscle:

I installed `neotest-python` from your repo with the `django-support` branch successfully like so:

```
{
    'nvim-neotest/neotest',
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
      "antoinemadec/FixCursorHold.nvim",
      { "afrischk/neotest-python", branch = "django-support" },
    },
    config = function()
      require('neotest').setup({
        adapters = {
          require("neotest-python")({
            env = { DJANGO_SETTINGS_MODULE = "AppName.settings" },
            dap = { justMyCode = false },
            args = { "--log-level", "DEBUG" },
            runner = "django",
          }),
        }
      })
    end
  }
```

FWIW I'm using lunarvim and lazy.nvim to test this out. 

That being said, I keep getting `no tests` found, but didn't have that issue with `pytest` in the past.

It's probably on my end, but wanted to ask in case it was useful QA / testing.

Completely understand if this isn't the right place to discuss, let me know if I should move this question elsewhere.

**Comment by afrischk** [comment] 2023-11-09 22:13
Hi @sampiecz 👋

thanks for reporting!

I currently have the feeling django rather has trouble detecting the tests than there is an issue with the plugin. Do you have a minimal example project so that I am able to reproduce?

**Comment by ikonitas** [comment] 2023-11-10 16:46
> Hi @sampiecz 👋
> 
> thanks for reporting!
> 
> I currently have the feeling django rather has trouble detecting the tests than there is an issue with the plugin. Do you have a minimal example project so that I am able to reproduce?

Great work! I can confirm that this is working, but the only issue I am having to pass argument like `--keepdb`

**Comment by afrischk** [comment] 2023-11-11 07:25
> > Hi @sampiecz 👋
> > 
> > thanks for reporting!
> > 
> > I currently have the feeling django rather has trouble detecting the tests than there is an issue with the plugin. Do you have a minimal example project so that I am able to reproduce?
> 
> Great work! I can confirm that this is working, but the only issue I am having to pass argument like `--keepdb` 

Thanks! Yah, i just expose `resultclass` and `verbosity` at the moment.

**Comment by sampiecz** [comment] 2023-11-20 20:33
> Hi @sampiecz 👋
> 
> thanks for reporting!
> 
> I currently have the feeling django rather has trouble detecting the tests than there is an issue with the plugin. Do you have a minimal example project so that I am able to reproduce?

Thank you @afrischk it's working on my end now too. Was simply due to test naming / file naming conventions.

**Comment by sampiecz** [comment] 2023-11-20 20:42
> Great work! I can confirm that this is working, but the only issue I am having to pass argument like `--keepdb`

+1 to the passing `--keepdb`, I haven't figured out how to do that, so I attach to the test and manually hit `yes/no`.

As a result, test runs are quite long, if anyone has a simple snippet to share it would be appreciated. 

I tried to grok the `runner  = ...` comment but wasn't sure how to modify my `config.lua` to use `DjangoUnittestRunner`.

**Comment by afrischk** [comment] 2023-12-11 06:11
#54

**Comment by sampiecz** [comment] 2023-12-15 18:20
Thank you so much @afrischk , that works! Really appreciate you taking the time to make & merge this PR :bow:

**Closed** 2023-12-20 18:38 UTC

**Comment by kenunq** [comment] 2024-04-21 18:19
https://github.com/kenunq/django-neotest

improved version, auto detect DJANGO_SETTINGS_MODULE, the names of the test files have been expanded

**Comment by ikonitas** [comment] 2024-08-21 15:56
This commit: https://github.com/nvim-neotest/neotest-python/commit/0ab9ad357075b8a7b516bf736b40854751b75845 broke the things with django runner while passing args `--keepd`

**Comment by metal3d** [comment] 2024-10-05 20:29
On my side, there is a problem while the `DJANGO_SETTINGS_MODULE` is not set. Maybe someone can merge the idea from @kenunq (sorry, your dependency fails on my configuration).
